name: ML
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - xgboost
  - tqdm
  - joblib
  - xgboost
  - prophet
  - neuralprophet=0.6.2
  - requests

